# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhm', '0002_auto_20160521_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='OrderTotalSum',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
