# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhm', '0003_auto_20160521_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHMMarketingSource',
            fields=[
                ('MarketingSourceId', models.AutoField(primary_key=True, serialize=False)),
                ('MarketingSourceName', models.CharField(max_length=200)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhm.DHMUser')),
            ],
        ),
        migrations.CreateModel(
            name='DHMProductType',
            fields=[
                ('ProductType', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTypeName', models.CharField(max_length=200)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhm.DHMUser')),
            ],
        ),
    ]
