# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhm', '0005_auto_20160525_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('AnimalId', models.AutoField(primary_key=True, serialize=False)),
                ('AnimalName', models.CharField(max_length=200)),
                ('AnimalSound', models.CharField(max_length=200)),
            ],
        ),
    ]
