# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhm', '0006_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
