# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhm', '0007_auto_20160531_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
